---
id: Service_Vimeo
name: Service_Vimeo
full: Vimeo client library
description: A client library for the Vimeo API.
list: dev
type: library
authors:
  -
    name: Michael J. Rubinsky
    user: mrubinsk
    email: mrubinsk@horde.org
    active: true
    role: lead
version:
  release: 1.0.0alpha1
  api: 1.0.0
state:
  release: beta
  api: beta
license:
  identifier: BSD-2-Clause
  uri: http://www.horde.org/licenses/bsd
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/Horde_Http: ^2
